WIP Issue #15: Login screen is missing
NandoTheessen/PM-Project-FrontEnd pull request #19
Opened 2018-11-20 07:04 UTC by honda0306

- [ ] Create Login screen HTML/Style
- [ ] Implement React Router to switch between main page and login
- [ ] Test functionality

2018-12-03 22:59 UTC, NandoTheessen requested changes
Made a few comments! 👍

2018-12-03 22:59 UTC, NandoTheessen commented on src/components/Jumbotron.js
> +        <h1>{props.title}</h1>
Here are the changes located, that we're not able to merge. 
Are you working on a new branch for this?

2018-12-03 22:59 UTC, NandoTheessen commented on src/components/Login.js
> +        .then(res => {
Looking good Chris! 👍 
It would be good if we could convert this to async / await syntax like the rest of the app.

Also, where do you think we should forward to after successful login? 
Should the shopping cart logic be held here, given that we are probably going into a different component and this one will get unmounted?

2018-12-04 16:33 UTC, honda0306 commented on src/components/Jumbotron.js
> +        <h1>{props.title}</h1>
Oh geez, no, I'm on master 🤦‍♂️ I'll go back and make a new branch and then move these changes in.

2018-12-04 19:39 UTC, NandoTheessen commented
Closing, new PR is #22

2018-12-04 19:39 UTC, closed without merging